services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: manhld2402/frontend
    container_name: frontend
    platform: linux/amd64
    volumes:
      - ".:/urs/share/nginx/html"
      - ".:/urs/share/nginx"
    ports:
      - "8080:80"
